language: python
python:
  - "2.7"
sudo: required
# install libtorrent
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y python-libtorrent
  - sudo apt-get install -y tor
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script: nosetests -s -v
